version: '3.9'

services:
  json-generator:
    image: massimocallisto/json-simulator:1.0.0
    volumes:
      - ./conf:/opt/app/json-data-generator/conf
    command: java -jar json-data-generator.jar simple_Simulator.json
